IF EXISTS (SELECT name FROM sys.databases WHERE name = N'ERStagingDB')
BEGIN
    ALTER DATABASE ERStagingDB SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE ERStagingDB;
END
GO

CREATE DATABASE ERStagingDB;
GO
