IF EXISTS (SELECT name FROM sys.databases WHERE name = N'ERStagindDB')
BEGIN
    ALTER DATABASE ERStagindDB SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE ERStagindDB;
END
GO

CREATE DATABASE ERStagindDB;
GO